#!/usr/bin/env bash
#Make a script using a while loop that echo Fizz on multiples of 3, Buzz on multiples of 5, and FizzBuzz on Multiples of 3 and 5.

x=1

while [ $x -le 100 ]
do
	if [ $((x % 3)) = 0 ] && [ $((x % 5)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((x % 3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((x % 5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$x"
	fi
	x=$((x+1))
done
