#!/usr/bin/env bash
#Script that tells rhe story of /etc/passwd

F= /etc/passwd



while FTS=: read -r user enpass uid gid desc home shell
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $enpass, more info about the user here: $desc"
	
done < $F
