#!/usr/bin/env bash
#Script that tells rhe story of /etc/passwd

LINE=$(cat /etc/passwd | grep $1)
IFS=:
set=LINE

while cat /etc/passwd
do
	echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"
done
