#!/usr/bin/env bash
#using a while loop to diplay Best School 8 times and bad luck at line 4 and good luck at line 8 
x=1
while [ $x -le 10 ]
	do
	if [ $x = 4 ]
	then
		echo "bad luck"
	elif [ $x = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
		x=$((x+1))
	fi
	done
