#!/usr/bin/env bash
#using a while loop to diplay Best School 8 times and bad luck at line 4 and good luck at line 8 
x=1
while [ $x -le 10 ]
	do
	if [[ $x = 1..3; 5..7; 9..10 ]]
	then
		echo "Best School"
	fi
	elif [[ $x = 4 ]]
	then
		echo "bad luck"
	else [[ $x = 8 ]]
		echo "good luck"
		x=$((x+1))
	done
