#!/usr/bin/env bash
# Making a while loop that uises case to echo on line 4, 9, 17.

x=1

while [ $x -le 20 ]
	do
		case $x in
			4)
				echo "$x"
				echo "bad luck from China";;
			9)
				echo "$x"
				echo "bad luck from Japan";;
			17)
				echo "$x"
				echo "bad luck from Italy";;
			*)
				echo "$x";;
		esac
		x=$((x+1))
	done
