#!/usr/bin/env bash
#making a script to see if a file exist, if its regular, and if its empty.

x=school

if [ -e "$x" ]
then
	echo "school file exists"
	if [ -s "$x"]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$x"]
	then
		echo "school is a regular file"
	else
		echo -n
	fi
else
	echo "school file does not exist"
fi
