#!/usr/bin/env bash
#making a for loop to see if a file exist, if its regular, and if its empty.
for x in *
do
	if [ -e "$x" ] && echo "school file exists" || echo "school file does not exist"
	then
		[ -s "$x" ] && echo "school file is not empty" || "school file is empty"
	then
		[ -f "$x" ] && echo "school is a regular file"
	fi
done
