#!/usr/bin/env bash
# Script that reacts to signals differently and deletes itself
x=1

echo $$ > /var/run/myscript.pid

while [ $x -ge 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	if trap 15
	then
		echo "I hate the kill command"
	elif trap 2
	then
		echo "Y U no love me?!"
	elif trap 3 15
	then
		rm -r /var/run/myscript.pid
	fi
done
