#!/usr/bin/env bash
# Script that reacts to signals differently and deletes itself
x=1
trap "echo I hate the kill command; rm -r /var/run/myscript.pid; exit" 15
trap "echo Y U no love me?!; exit" 2
trap "rm -r /var/run/myscript.pid; exit" 3

echo $$ > /var/run/myscript.pid

while [ $x -ge 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done


### trap "echo dont bother!; rm life.get; exit" 8i
