#!/usr/bin/env bash
# working with sudo to manage /manage_my_process

case "$1" in

	start)
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
		sudo  ./manage_my_process start
esac
