#!/usr/bin/env bash
# working with sudo to manage /manage_my_process

case "$1" in
	"start")
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;

	"stop")
		echo "manage_my_process stopped"
		kill $(cat manage_my_process)
		rm -r /var/run/my_process.pid
		;;
	
	"restart")
		echo "manage_my_process restarted"
		kill $(cat manage_my_process)
		rm -r /var/run/my_process.pid
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		;;

	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
